// swift-tools-version: 5.9
// Auto-generated at release time from Scripts/binary-package.swift.tmpl.
// Do not edit this file on `main` — it only exists at release tag commits.
// See Scripts/binary-package.swift.tmpl and .github/workflows/release.yml.
import PackageDescription

let release = "v1.0.2"
let checksum = "10c186cbcdcd5579c8cfc6cad076f07f1223c92047cf2885464e72ccde25a464"

let package = Package(
    name: "TagLibSPM",
    platforms: [
        .macOS(.v12),
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "TagLib",
            targets: ["TagLib"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "TagLib",
            url: "https://github.com/thebytearray/TagLib-spm/releases/download/\(release)/TagLib.xcframework.zip",
            checksum: checksum
        ),
    ]
)
